FROM node:20-alpine

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ .

RUN npm run build

# Use serve to host the built files
RUN npm install -g serve
CMD ["serve", "-s", "dist", "-l", "3000"]
